<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hobbyreadings</name>
   <tag></tag>
   <elementGuidId>f947b1e7-ab11-4f8b-a9c4-911585b0fb24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbies-checkbox-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies-checkbox-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5efbb28-d8eb-4cef-a61f-e022f8459d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies-checkbox-2</value>
      <webElementGuid>a7c0ba29-c6fb-4d54-b0ed-93f6017ad828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>6baa1b17-7c49-4355-8849-3d2cfc97fbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>37985aeb-dbda-408b-aca9-c44f30be335d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a6fffbed-51fd-4f71-99ba-5f67251e3c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies-checkbox-2&quot;)</value>
      <webElementGuid>7518d337-e9b0-488a-9712-98cd777dfb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies-checkbox-2']</value>
      <webElementGuid>06f07935-3b07-4ee9-9e34-89839a4e926a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hobbiesWrapper']/div[2]/div[2]/input</value>
      <webElementGuid>9db059be-2cfb-4342-963a-d193feac7d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/input</value>
      <webElementGuid>364e0e7a-6612-4f8e-a44d-c0aab6234bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hobbies-checkbox-2' and @type = 'checkbox']</value>
      <webElementGuid>e5410a2b-a5d9-4c2f-85f3-cb51a55a60f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
